[package]
name = "ferrix"
version = "0.1.6"
edition = "2024"
repository = "https://github.com/KwentiN-ui/ferrix.git"

[dependencies]
aho-corasick = "1.1.4"
chrono = "0.4.42"
clap = { version = "4.5.54", features = ["derive"] }
derive_more = {version="2.1.1", features=["full"]}
faer = "0.23.2"
indicatif = "0.18.3"
itertools = "0.14.0"
nalgebra = "0.34.1"
rayon = "1.11.0"
sprs = "0.11.4"
strum = {version="0.27.2", features=["derive"]}
strum_macros = "0.27.2"
thiserror = "2.0.17"

[lints.rust]
# unused = "allow"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
collapsible_if = "allow"
similar_names = "allow"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
